{
    'name': 'Training Student',
    'version': '1.0',
    'summary': 'Student Training Management',
    'description': 'Manage students, courses and enrollments',
    'author': 'Peal-wb',
    'category': 'Training',
    'depends': ['base', 'mail'],
    'data': [
        'security/training_security.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'data/cron.xml',
        'data/student_email_template.xml',
        'views/training_student_views.xml',
        'views/enrollment_views.xml',
        'views/course_views.xml',
    ],
    'demo': [
        'demo/course_demo.xml',
        'demo/demo.xml',
    ],
    'installable': True,
    'application': True,
}
